---
# This will do the ssh-copy-id step for current user so cap can deploy.
# Other devs will need to look up deploy user password in PassPack and run ssh-copy-id.
- name: Set authorized key for remote user copying it from current user
  authorized_key:
    user: "{{ app_user }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  become: yes

# IS&T sets AllowUsers in sshd config by default. So let's go with that and add
# that line with current ansible and app users.
# Source: https://stackoverflow.com/a/31436781/6763239
# See also: https://github.com/chapmanu/imposter/blob/development/devops/ansible/roles/ssh/tasks/main.yml
- name: Add users to sshd_config AllowUsers line
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AllowUsers'
    line: "AllowUsers {{ ansible_user }} {{ app_user }}"
  become: yes
  notify: Reload ssh service
