#
# Common tasks for provisioning a new Red Hat server.
#
---
- name: "Install required Yum packages."
  yum: name={{ item }} state=latest
  with_items:
    - python
    - python-setuptools
    - python-setuptools-devel
    - logrotate

- name: "Install pip with easy_install."
  easy_install: name=pip state=latest

- name: "Install required Python packages."
  pip: name={{ item }}
  with_items:
    - pyopenssl

# This is required for the rbenv role. CentOS is ok but Red Hat requires extra repo.
# See https://github.com/zzet/ansible-rbenv-role/issues/109
# Source: https://github.com/tjtoml/mattermost-ansible/blob/master/roles/letsencrypt/tasks/main.yml
- name: Enable RHEL 7 Server Optional RPMs (RHEL 7 only)
  command: subscription-manager repos --enable rhel-7-server-optional-rpms
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")